### PR TITLE
Add Responsiveness to Cart Page

### PR DESCRIPTION
**Pull request by varun13169**
Add Responsiveness to Cart Page

### CODE REVIEW

**Comment by saurabhan** [comment]
Deploy preview is not working, can't see UI changes.

**Review by tonymike99 — APPROVED** [review]
Very few lines modified and all looks good!

**Comment by varun13169** [comment]
> Deploy preview is not working, can't see UI changes.

It's working
https://deploy-preview-13--gardenkart.netlify.app/pages/cartpage/cartpage

**Review by saurabhan — APPROVED** [review]
Clean ui and code, approved

**Pull request merged**
